baseURL:  https://catherine-portfolio.netlify.app/
languageCode: en-us
title: Portfolio website for Catherine Xinyue Zhang
theme: Catherine Zhang
googleAnalytics: ''
disqusShortname: ''
params: 
  banner:
    buttonText: Get Started
    subtitle: |- 
        Master in Financial Analysis student at London Business School (LBS)
     
    title: Hi, my name is Catherine Zhang 
  blog: {}
  contact:
    address: 
      - city: London, ST NW8 6EX
        country: London
        street: Baker Street
        title: address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: catherinez.mfa2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (+86) 156-1109-1201
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: 
    enable: yes
    quicklinks: 
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-twitter
        label: Twitter
        url: https://www.twitter.com
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com
      - icon: fa-github
        label: GitHub
        url: https://github.com/CatherineZhangXY?tab=repositories
      - icon: fa-linkedin
        label: LinkedIn
        url: www.linkedin.com/in/xinyue-zhang-catherine
  image: banner.jpg
  name: Xinyue-Zhang-Catherine
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: Generic Blog
        url: blogs/ipsum
      - name: Excurricular Activities
        url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: ID photo.jpg
        subtitle: Background Information
        title: About Me
        url: blogs/Xinyue Zhang (Catherine) CV.pdf
      - image: Education.jpg
        subtitle: Education Background
        title: Diverse Academic Experience
        url: blogs/EducationBackground.jpeg
      - image: Professionalphoto.jpg
        subtitle: Internships
        title: Professional Work Experience
        url: blogs/Internship-1.jpg
      - image: Airbnb.jpg
        subtitle: Group Data Analysis Project
        title: AirBnB Prices in Vienna (Data Analytics Group Assignment) 
        url: blogs/ca09_group3_project_vF.html
      - image: higherEducation.jpg
        subtitle: Research Topic of Higher Education Under the Pandemic
        title: Covid-19 & The Rise Of Micro-Credentials
        url: blogs/Accenture-Group-Report-Micro-Credentials.pdf
      - image: stock.jpg
        subtitle: Returns of financial stocks
        title: Dow Jones Industrial Average (DJIA) Stocks Risk Return
        url: blogs/risk_return.html
      - image: selfphoto.jpg
        subtitle: Lifestyle & Interest
        title: Excurricular Activities
        url: blogs/Life.jpg
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "Hello! My name is Catherine. I am currently a postgraduate student at London Business School Master in Financial Analysis program. I previous studied finance and business analytics at the University of Sydney in Australia, and had a semester exchange to the Wharton Business School, UPenn. This diverse academic experiences not only equipped me with comprehensive knowledge in equity, fixed income, and capital market, but also arose my keen interest in this financial sector. I also gradually realize that finance is widely used in our daily life, and learning finance is helpful to our financial decision-making and improves my understanding of the market operation. 
My distinct academic performances lied me solid foundations in finance, which brought me great confidence to perform well as the Asset Management Program. 
Later on, I further enhanced my professional skills and strengthened my passion in the financial sector after my previous internships. During my two most recent banking internships at CICC and Huatai, I participated in live deals of A-share and Hong Kong IPOs for our global clients. Specifically, I worked in a team with 6 colleages to prepare pitchbooks and valuation materials, and analyzed various TMT & real estate companies. I also evaluated a U.S. top SaaS company regarding business highlights, financial performance, and industry competition and delivered presentation to the management team. Moreover, I accumulated asset management experience from industrial projects. In the project of managing 9 US funds, I established 5-factor regression models, and used asset allocation strategies to come up with the optimal portfolio with 23% return against investor’s risk tolerance. 
."
    title: Self Introduction
    url: blogs
